### ISSUE TITLE
Nav + menu

### ISSUE THREAD

**Issue by sdvinov** [sdvinov/portfolio#1]
![nav](https://pp.userapi.com/c837522/v837522363/41335/YSzBCgDPvrA.jpg)

```css
h2.entry-title {
  display: none;
}

div.custom-header {
  background: url('https://pp.userapi.com/c837522/v837522363/4132b/cLQRIO3kP0w.jpg');
  background-position: center left;
  background-repeat: no-repeat;
  background-size: cover;
}

h1.site-title a, div.site-branding-text p {
  color: #fff;
}
```

**Comment by sdvinov** [comment]
UPDATED:

![img](https://pp.userapi.com/c639424/v639424363/242e4/DsJKQqgZIWU.jpg)

```css
/* Header */
header.entry-header {
  display: none;
}

div.custom-header {
  background: url('https://pp.userapi.com/c837522/v837522363/4132b/cLQRIO3kP0w.jpg');
  background-position: center left;
  background-repeat: no-repeat;
  background-size: cover;
}

img.custom-logo {
  margin-top: 25px;
}

.colors-dark .site-description, .site-title a {
  color: #fff !important;
  text-shadow: 0 0 3px #000;
}
```

**Comment by sdvinov** [comment]
```css
/* Navigation */

.navigation-top {
  border: 0;
  background: #333 !important;
  font-size: 1.5em;
  box-shadow: 0 0 5px #000;
  text-transform: uppercase;
}

.navigation-top a {
  padding-top: 0;
  padding-bottom: 0;
}

ul#top-menu {
  text-align: center;
  background: #333;
}
```
