### ISSUE TITLE
Featured work

### ISSUE THREAD

**Issue by sdvinov** [sdvinov/portfolio#2]
![img](https://pp.userapi.com/c639424/v639424363/23f78/32hITcQn-9E.jpg)

```css
.featured-work-item {
  display: inline;
  width: 200px;
  float: left;
  text-align: center;
  margin: 7px;
  transition: all .5s ease;
}

.featured-work-item img {
  box-shadow: 0 0 2px #000 !important;
}

.featured-work-item:hover {
  transform: scale(1.05,1.05);
}

.featured-work-item a {
  border:0;
}
```

**Comment by sdvinov** [comment]
UPDATED:
![img](https://pp.userapi.com/c639424/v639424363/242ee/gvI6jJEXsSg.jpg)

```css
/* Featured */

.featured-work-item {
  display: inline;
  width: 200px;
  float: left;
  text-align: center;
  margin: 7px;
  background: #666;
  border: 10px solid #333;
  transition: all .5s ease;
  padding-left: 20px;
  padding-right: 20px;
  height: 239px;
}

.featured-work-item:hover {
  transform: scale(1.05,1.05);
}

.featured-work-item a {
  border:0;
}

.tech-icons {
  display: inline;
  float:left;
  width: 25%;
}
```
