### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by sdvinov** [sdvinov/portfolio#3]
![img](https://pp.userapi.com/c639424/v639424363/242f8/DTlxzk757y0.jpg)
![img](https://pp.userapi.com/c639424/v639424363/24302/ep4jNSSIGZQ.jpg)

```css
/* Sections */

.highlight-section {
  border: 20px solid #333;
  padding: 20px;
  background: #555;
  overflow: hidden;
  box-shadow: 0 0 5px #000;
  margin-top: 20px;
}

.highlight-section p, .highlight-section ul {
  margin-bottom: 0;
}

.highlight-section ul li {
  margin-left: 20px
}

.highlight-section img {
  transition: all .5s ease;
}

.highlight-section img:hover {
  transform: scale(1.05,1.05);
}

#aboutme h2 {
  padding-top: 100px
}

.my-photo {
  width: 100%;
  display: block;
  border: 2px solid #333;
}

.my-photo:hover {
  transform: scale(1,1) !important;
}
```
