### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by sdvinov** [sdvinov/portfolio#4]
![img](https://pp.userapi.com/c639424/v639424363/2430c/TfioEIi46Fk.jpg)

```css
/* Form */
.wpcf7-submit {
  width: 100%;
  font-size: 1.3em !important;
}

input[name="your-name"] {
  margin-top: 20px;
}
```

The rest is default.
