### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by sdvinov** [sdvinov/portfolio#5]
![img](https://pp.userapi.com/c639424/v639424363/24316/tH2oz6sy1cM.jpg)

```css
/* Footer */

footer {
  background: #333;
}

footer p {
  text-align: right;
}

footer ul {
  float: left;
  margin-left: 100px;
}

footer ul li {
  list-style-type: none;
  font-size: 1.3em !important;
  padding-bottom: 10px;
}

footer {
  font-size: 1.3em !important;
  box-shadow: 0 0 5px #000;
}

.copy {
  text-align: center;
}
```
