### ISSUE TITLE
Project Example

### ISSUE THREAD

**Issue by sdvinov** [sdvinov/portfolio#6]
![img](https://pp.userapi.com/c639424/v639424363/24324/dm55hKUeuZA.jpg)

In addition to existing CSS:

```css
/* Project info */
.project-info  li {
  list-style-type: none;
  font-size: 2em;
  padding:
}
```
